export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_JOTAPI = 'UPDATE_JOTAPI'
export const UPDATE_PHOTO = 'UPDATE_PHOTO'
export const UPDATE_FORMS = "UPDATE_FORMS"